"""add_location_id_to_products

Revision ID: 1c49a8f0fad6
Revises: 9e996b729073
Create Date: 2026-03-20 14:48:25.792452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c49a8f0fad6'
down_revision: Union[str, Sequence[str], None] = '9e996b729073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_location_id'), 'products', ['location_id'], unique=False)
    op.create_foreign_key(None, 'products', 'warehouse_locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_location_id'), table_name='products')
    op.drop_column('products', 'location_id')
    # ### end Alembic commands ###
