"""add_mercadolibre_accounts

Revision ID: 4924bea2d9c9
Revises: b90bf512090e
Create Date: 2026-03-21 17:05:47.855966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4924bea2d9c9'
down_revision: Union[str, Sequence[str], None] = 'b90bf512090e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mercadolibre_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('ml_user_id', sa.String(length=50), nullable=False),
    sa.Column('ml_nickname', sa.String(length=200), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mercadolibre_accounts_client_id'), 'mercadolibre_accounts', ['client_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mercadolibre_accounts_client_id'), table_name='mercadolibre_accounts')
    op.drop_table('mercadolibre_accounts')
    # ### end Alembic commands ###
