"""add_dispatch_batch

Revision ID: 9e996b729073
Revises: 65c4594e200d
Create Date: 2026-03-20 13:54:29.012039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e996b729073'
down_revision: Union[str, Sequence[str], None] = '65c4594e200d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=20), nullable=False),
    sa.Column('carrier', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('dispatched_by', sa.Integer(), nullable=True),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispatched_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_batches_batch_number'), 'dispatch_batches', ['batch_number'], unique=True)
    op.add_column('orders', sa.Column('dispatch_batch_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_dispatch_batch_id'), 'orders', ['dispatch_batch_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'dispatch_batches', ['dispatch_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_dispatch_batch_id'), table_name='orders')
    op.drop_column('orders', 'dispatch_batch_id')
    op.drop_index(op.f('ix_dispatch_batches_batch_number'), table_name='dispatch_batches')
    op.drop_table('dispatch_batches')
    # ### end Alembic commands ###
