"""add_dominant_zone_to_orders

Revision ID: a3c005e64767
Revises: f18c087d9f2b
Create Date: 2026-03-21 13:16:43.712136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c005e64767'
down_revision: Union[str, Sequence[str], None] = 'f18c087d9f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('dominant_zone', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_orders_dominant_zone'), 'orders', ['dominant_zone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_dominant_zone'), table_name='orders')
    op.drop_column('orders', 'dominant_zone')
    # ### end Alembic commands ###
