"""add_transporters

Revision ID: b23c2499ad8d
Revises: b4c8d2e3f5a6
Create Date: 2026-03-21 12:36:59.582411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23c2499ad8d'
down_revision: Union[str, Sequence[str], None] = 'b4c8d2e3f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transporters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('camioneta', 'moto', 'correo', name='transportertype'), nullable=True),
    sa.Column('zone', sa.Enum('caba', 'gba', 'interior', name='transporterzone'), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transporters')
    # ### end Alembic commands ###
