"""add_dispatch_verifications

Revision ID: b90bf512090e
Revises: eb873c795b36
Create Date: 2026-03-21 16:21:42.666018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b90bf512090e'
down_revision: Union[str, Sequence[str], None] = 'eb873c795b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('entered_count', sa.Integer(), nullable=False),
    sa.Column('expected_count', sa.Integer(), nullable=False),
    sa.Column('is_match', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['dispatch_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_verifications_batch_id'), 'dispatch_verifications', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_verifications_batch_id'), table_name='dispatch_verifications')
    op.drop_table('dispatch_verifications')
    # ### end Alembic commands ###
