"""add_transporter_id_to_dispatch_batches

Revision ID: f18c087d9f2b
Revises: b23c2499ad8d
Create Date: 2026-03-21 12:37:52.186655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18c087d9f2b'
down_revision: Union[str, Sequence[str], None] = 'b23c2499ad8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispatch_batches', sa.Column('transporter_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_dispatch_batches_transporter_id'), 'dispatch_batches', ['transporter_id'], unique=False)
    op.create_foreign_key(None, 'dispatch_batches', 'transporters', ['transporter_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dispatch_batches', type_='foreignkey')
    op.drop_index(op.f('ix_dispatch_batches_transporter_id'), table_name='dispatch_batches')
    op.drop_column('dispatch_batches', 'transporter_id')
    # ### end Alembic commands ###
